services:
  - type: web
    name: finvest-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false # à définir dans le dashboard Render
      - key: APP_BASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_COOKIE_NAME
        value: token
